name: Build Native Binaries
on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Windows x86_64
          - target: x86_64-pc-windows-gnu
            os: windows-latest
            artifact_name: buildc-windows-x64.exe
          # Windows arm64
          - target: aarch64-pc-windows-msvc
            os: windows-latest
            artifact_name: buildc-windows-arm64.exe
          # MacOS x86_64
          - target: x86_64-apple-darwin
            os: macos-latest
            artifact_name: buildc-macos-x64
          # MacOS arm64
          - target: aarch64-apple-darwin
            os: macos-latest
            artifact_name: buildc-macos-arm64
          # Linux x86_64
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            artifact_name: buildc-linux-x64
          # Linux arm64
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            artifact_name: buildc-linux-arm64
            cross: true # ARM builds are failing at the linker step, but works when using cross!
    steps:
      # Checkout and pull changes from previous jobs
      - uses: actions/checkout@v4
      - run: git pull
      # Setup
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Install Cross
        if: matrix.cross == true
        run: cargo install cross
      # Build
      - name: Build (Native)
        if: matrix.cross != true
        run: cargo build --release --target ${{ matrix.target }}
      - name: Build (Cross)
        if: matrix.cross == true
        run: cross build --release --target ${{ matrix.target }}
      - name: Rename buildc (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir dist
          mv target/${{ matrix.target }}/release/aklinker1_buildc.exe dist/${{ matrix.artifact_name }}
        shell: bash
      - name: Rename buildc (Unix)
        if: runner.os != 'Windows'
        run: |
          mkdir dist
          mv target/${{ matrix.target }}/release/aklinker1_buildc dist/${{ matrix.artifact_name }}
      # Signing: TODO
      # Upload
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/${{ matrix.artifact_name }}
